### ISSUE TITLE
getAvailablePurchases() returns empty array

### ISSUE THREAD

**Issue by Symyon** [dooboolab/react-native-iap#122]
### Version of react-native-iap
0.3.10

### Platforms you faced the error (IOS or Android or both?)
iOS, did not tried on Android yet

### Expected behavior
Get all the unconsumed purchases.

### Actual behavior
I get [] 

### Steps to reproduce the behavior
on iOS buy some consumable items. Try to buy again, it says these are already bought, so restoring.
Trying to get getAvailablePurchases() to be able to consume that will give an empty array.

**Comment by Symyon** [comment]
OK, I had to "prepare" the RNIap first.

**Comment by dooboolab** [comment]
@Symyon This is strange because nothing will happen in ios for `prepare` method. This only affects android billing service to start. Maybe there could be some delay in ios payment to update your products.

**Comment by companytest1206** [comment]
@dooboolab I am receiving same error in android. I have added **prepare** method but stills it returns empty array.

**Comment by Symyon** [comment]
@dooboolab  Sorry for the delay. And for the misunderstanding.
My question/issue is for iOS, but my comment with "prepare" is for Android.

So on iOS I am unable to consume my purchased items and for that reason I am unable to re-buy.
getAvailablePurchases() is an empty array.

For Android I also had the problem getting available purchases,  but that was solved with "prepare".

I am still debugging the iOS issue, but any help will be appreciated.

 Also on iOS is taking a huge amount of time to wait for the systems dialog (Are you sure to buy, You already bought/restoring etc). It is like 10-20 seconds. Than at some point they are all coming one after another for the action I did (e.g. taping more than one item to buy while app is waiting)

**Comment by noahhayes** [comment]
I have the same issue. I was wondering if it had something to do with not calling finishTransaction or because I'm using a sandbox user.

**Comment by noahhayes** [comment]
hey @Symyon not sure if you figured it out... but for anyone else that needs help, the solution is to make sure you're not signed into a sandbox testing account. Once I signed into my real Apple account, getAvailablePurchases prompted me to authenticate correctly.

**Comment by noahhayes** [comment]
Okay another update. So the problem came back and then I was able to make it work after I signed out of my apple account and signed back in as the sandbox. Something about signing in and out seems to reset it.

**Comment by voidstarfire** [comment]
If you use the Prepare method it will crash on release for Android fyi. I'm stuck now cache. Can't use prepare on release APK. Can't validate subscriptions.
