### ISSUE TITLE
getProducts always return null

### ISSUE THREAD

**Issue by companytest1206** [dooboolab/react-native-iap#124]
@dooboolab I am receiving null array after calling getProducts method after prepare method.

**Comment by dooboolab** [comment]
@companytest1206 This should not happen. Could you please share more information? Such as your codes, your products status, os, devices, and etc. For in-app products configuration, please refer to [blog](https://medium.com/@dooboolab/react-native-in-app-purchase-121622d26b67).

**Comment by companytest1206** [comment]
Here is my code..

`async componentDidMount() {
    try {
      await RNIap.prepare();
      const products = await RNIap.getProducts(itemSkus);
      console.log('Products', products);
    }
    catch (err) {
      console.warn(err.code, err.message);
    }
    this.fetchData();
   
  }`

My app status is in alpha mode. Using nexus 6 for debugging.

**Comment by dooboolab** [comment]
@companytest1206 Your code seems fine. What about your product configuration in `playstore` or `itunesconnect`?

**Comment by sanilcgs** [comment]
I have the same issue.

**Comment by dooboolab** [comment]
@systemride @sanilcgs Could you please share the platforms you are having trouble with using `getProducts` method?

**Comment by axelkennedal** [comment]
I'm having trouble with this on Android 7.0 (running on an LG G6), developing on MacOS 10.13.4 @dooboolab

**Comment by sanilcgs** [comment]
Created my app using **create-react-native-app** package. For integrating in-app purchase I have detached my app. After that I integrated **react-native-iap** into my app. For me the issue is happened in both iOS and android. I am using Android Studio 3.0.1 and Xcode 9.3.  @dooboolab

**Comment by axelkennedal** [comment]
According to [https://github.com/idehub/react-native-billing](this README) of another library it should be possible to get the available products when running in a debug environment (not an Alpha/Beta release), is that correct? (I'm thinking it should be the same for this library as that probably is dependant on how Google handles the IAP).

**Comment by axelkennedal** [comment]
Another related question; should the SKUs be prefixed with the package name? In other words; is "unlock_premium" or "com.kimer.unlock_premium" correct when the ID I have specified in Google Play Console is "unlock_premium"?

**Comment by vadermemo** [comment]
@axelkennedal The SKUS don´t have any format, are totally customizables. In few words: "unlock_premium" or "com.kimer.unlock_premium"  are correct.

**Comment by axelkennedal** [comment]
**UPDATE:**
It is now working for me 😄! I tried a couple of things but I'm not sure what was key to getting it to work 🤔 This is anyways what I did:

1. Reinstalled the package
2. Changed my import statement from `import InAppPurchase from "react-native-iap;" to "import * as InAppPurchase from 'react-native-iap';"`
3. Changed my SKU in the code from "com.kimer.unlock_premium" to "unlock_premium"

**Comment by vadermemo** [comment]
@axelkennedal  you must use any name, but you must use on Google Play Console> your application > Google Play store> in app products. And the SAME name you must use on source code.

**Comment by sanilcgs** [comment]
@dooboolab When I am trying to execute RNIap.buyProduct('*****') with my productID, I got the error message **That item is unavailable**. Actually my managed product is in active state. What will be the issue? I can able to list the product details using RNIap.getProducts(itemSkus). Do I need to add the license key into my app??

**Comment by dooboolab** [comment]
@sanilcgs could you tell me which platform you are facing error?

**Comment by dooboolab** [comment]
@sanilcgs are you using our newer module which is ‘0.3.23’? Also similar issue can be found here. https://github.com/dooboolab/react-native-iap/issues/142

**Comment by sanilcgs** [comment]
@dooboolab  Yes I'm using '0.3.23'. My problem is now with **RNIap.buyProduct('*****')**. I got this error **'Error: That item is unavailable.'**.  Currently I have released my alpha version and published it to google play.

**Comment by dooboolab** [comment]
@sanilcgs I posted some help info for that in above issue. I will paste here again. Please check below.

             Do's
1)Create sign apk for your application.
2)Upload your apk on Google play store.
3)Create product for your application.
4)wait for 6-12 hour for update item's on store.
5)Give Billing permissions in Manifest.xml

               Don't
1)Don't use emulator for testing its does not support Billing Services.
2)Don't use unsigned apk for Billing services.

Read more: http://www.androidhub4you.com/2013/03/how-to-inegrate-in-app-purchase-billing.html#ixzz5DqRctVJp

**Comment by sanilcgs** [comment]
@dooboolab As I already said that my app is not released to production. Now I have released my alpha version only. So can I test this **RNIap.buyProduct('********')** with my alpha version or do I need to release my production for testing purchase???

**Comment by dooboolab** [comment]
@sanilcga If you read above throughly, you should be aware you do not need to release apk to production. Just alpha or beta is fine but your apk should be signed as explained. Check above once more and see what you are missing first.

**Comment by systemride** [comment]
@dooboolab The do's and don'ts above are helpful. For noobs, this would be really helpful to explain in the documentation that you can only test this on an alpha/beta release and if you test this in a dev build on emulator, it will always return an empty array. I see no mention of that anywhere. I'm happy to add this in a pull request if you'd like?

**Comment by dooboolab** [comment]
@systemride Any PR is appreciated!

**Comment by mayankbaiswar-CSE** [comment]
@axelkennedal did all those things, I'm still getting an empty array. Any ideas?

**Comment by JJMoon** [comment]
@axelkennedal `getProducts()` in iOS works well on simulator. Purchasing actions should be test on the real device with sandbox apple account.

**Comment by axelkennedal** [comment]
@JJMoon if you read my comments you would have known I'm on Android, not iOS.

**Comment by raduflp** [comment]
@axelkennedal being passive aggressive with the people who voluntarily spend their precious time trying to help you will not get you a long way. 

@JJMoon @dooboolab  thank you for the great work

**Comment by axelkennedal** [comment]
@raduflp lol what are you talking about? I just pointed out that we are on different platforms

**Comment by dooboolab** [comment]
@raduflp Thank you for your kind response and concern. I don't think @axelkennedal meant it to be aggressive. He is just too overwhelmed using `react-native-iap`. Feel like this issue can be closed so I'll close it. Also, any PR is appreciated that may help new generations.

**Comment by NarekChang** [comment]
Try it. Work for me:

"You need additionally add your testing account to another special list of accounts "Gmail accounts with testing access", you can find that on play account setting(not project!). On the page where you can see a list of your projects go to settings, and then on "Account details" page (scroll down, it's almost in the bottom of page) you will find the "Gmail accounts with testing access" list."

Set up application licensing
To set up application licensing, start by adding your list of tester's Gmail addresses in the Play Console.

Go to your Play Console.
Select Settings Settings > Account details.
Under "License Testing," add your testers' Gmail addresses.
At the top of the screen, select Save.

**Comment by ShridharCodewave** [comment]
I have integrated the react-native-iap and uploaded my signed apk to beta release on play store and also added one subscription plan. I am trying to get the list of subscription by subscription ID in debug mode which is always returning an empty array. Can I actually test the subscription in debug mode?

**Comment by NarekChang** [comment]
@ShridharCodewave you use real device or simulator?

**Comment by ShridharCodewave** [comment]
@NarekChang  I use real device

**Comment by roots-ai** [comment]
[iOS] Is it possible to get the product in `getProducts` without the product being submitted for review?
If yes, then I am getting `getProducts` as an empty array

**Comment by glinda93** [comment]
It's not clearly stated in the document but you need to fetch subscriptions with `getSubscriptions` method.

`getProducts` can get products and subscriptions in iOS but in android, `getProducts` cannot fetch subscriptions.

**Comment by yemd** [comment]
I have the exact same issue, my signed bundle is on the alpha channel (unreviewed), I tried both Release builds, Debug builds, Simulator, Real device, I can fetch the subscriptions correctly but impossible to make a purchase.  

Should I wait for Apple to review the alpha release first?

**Comment by deepanshu01399** [comment]
> @NarekChang I use real device and now somehow I am getting the subscriptions.

are you able to get the subscriptions list in your debug build or you need to make a release build to test the subscription list

**Comment by arindoneATK** [comment]
getSubscriptions is returning an error right now on android "subscriptionOffers are required for Google Play Subscriptions"

**Comment by rafaelbpa** [comment]
> > @NarekChang I use real device and now somehow I am getting the subscriptions.
> 
> are you able to get the subscriptions list in your debug build or you need to make a release build to test the subscription list

Did you figure out? I'm baffled by this. Why is so hard to retrieve a simple list of subscriptions? Do we need to publish the app, submitting a signed apk/aab, to TEST/IMPLEMENT our subscriptions? OMG, I almost can't believe it.

**Comment by NarekChang** [comment]
> > > @NarekChang I use real device and now somehow I am getting the subscriptions.
> > 
> > 
> > are you able to get the subscriptions list in your debug build or you need to make a release build to test the subscription list
> 
> Did you figure out? I'm baffled by this. Why is so hard to retrieve a simple list of subscriptions? Do we need to publish the app, submitting a signed apk/aab, to TEST/IMPLEMENT our subscriptions? OMG, I almost can't believe it.
> 
> btw, how you debug the apk from the play store? Am I confused or what..?

I solved this problem, use hooks https://react-native-iap.dooboolab.com/docs/api-reference/hooks

**Comment by ZeeshanAhmadKhalil** [comment]
I just restarted the app and the issue got solved.

**Comment by c-info** [comment]
I have added the app on internal testing still i haven't got data on the product array. do I need to upload the app to alpha or beta testing?

**Comment by radiosilence** [comment]
I'm using a real device but I am wanting to develop the code for IAP on Android so I am using the debug version (e.g. `react-native run-android`, and getting the `E_ITEM_UNAVAILABLE` error.

Do I really have to only develop using a signed build? How exactly does that work, surely it would make development take forever and I wouldn't be able to debug my app as I work?!

**Comment by bharathy-kannan** [comment]
> > > > @NarekChang I use real device and now somehow I am getting the subscriptions.
> > > 
> > > 
> > > are you able to get the subscriptions list in your debug build or you need to make a release build to test the subscription list
> > 
> > 
> > Did you figure out? I'm baffled by this. Why is so hard to retrieve a simple list of subscriptions? Do we need to publish the app, submitting a signed apk/aab, to TEST/IMPLEMENT our subscriptions? OMG, I almost can't believe it.
> > btw, how you debug the apk from the play store? Am I confused or what..?
> 
> I solved this problem, use hooks https://react-native-iap.dooboolab.com/docs/api-reference/hooks

I am unable to get it working with hooks. It gives undefined when I use getSubscriptions. Did you use the debug app or did you try in closed testing directly? Any help is highly appreciated as I have been struggling for the past 4 days with this.

**Comment by sanaf1333** [comment]
@hyochan  and others, will I be able to get subscriptions on physcial device before the app in closed testing has been reviewed. I have submitted it for review so meanwhile will I get subscriptions on physical device?
Currently I am getting []
