### ISSUE TITLE
Migrate to Google Play Billing Library 5

### ISSUE THREAD

**Issue by SimonDamberg** [dooboolab/react-native-iap#1710]
Would be great if we could use the new features in the latest version :)
 
[Migration Guide](https://developer.android.com/google/play/billing/migrate-gpblv5)
[Compatability Guide](https://developer.android.com/google/play/billing/compatibility)

**Comment by PaxLyj** [comment]
Really needs this update. Is there any plan?

**Comment by jkfurog** [comment]
Yeah , same here. One of our requirements is to implement IAP discount on both android and IOS

**Comment by andresesfm** [comment]
Migrated here: https://github.com/dooboolab/react-native-iap/pull/1762/files
Looks like the API is backwards compatible

**Comment by jkfurog** [comment]
hi @andresesfm , is it possible also to use the `queryProductDetailsAsync` instead of the deprecated `querySkuDetailsAsync`? the main reason I am requesting is that the  `queryProductDetailsAsync` is now returning the promos for that subscription

**Comment by andresesfm** [comment]
@jkfurog please take a look at the updated PR

**Comment by jkfurog** [comment]
hi @andresesfm I am encountering this issue after U upgrade to v9.0.0-beta

```
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file '***/node_modules/react-native-iap/android/build.gradle' line: 19

* What went wrong:
A problem occurred evaluating project ':react-native-iap'.
> Failed to apply plugin 'kotlin-android'.
   > The current Gradle version 6.7 is not compatible with the Kotlin Gradle plugin. Please use Gradle 6.7.1 or newer, or the previous version of the Kotlin plugin.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':react-native-iap'.
> compileSdkVersion is not specified. Please add it to build.gradle

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 56s
```

**Comment by andresesfm** [comment]
It's strange because CI is passing. Are you overriding the Google Play billing version on your gradle files @jkfurog ?

**Comment by jkfurog** [comment]
nope I am not @andresesfm , I was able to make it work by modifying this
<img width="743" alt="image" src="https://user-images.githubusercontent.com/103121173/181411370-eff99eb4-e4a4-456f-a1e4-52913797f374.png">


however I am now encountering this issue when I am trying to do : `IAP.setAndroidNativeModule(NativeModules.RNIapModule)`

it says : `[TypeError: _reactNativeIap.default.setAndroidNativeModule is not a function. (In '_reactNativeIap.default.setAndroidNativeModule(_reactNative.NativeModules.RNIapModule)', '_reactNativeIap.default.setAndroidNativeModule' is undefined)]`

**Comment by andresesfm** [comment]
Thank you for reporting the native issue. About the J's issues. Can you please check iap.js inside your node_modules. I'm thinking maybe I misspelled the name of the setter.

I'll run some tests and push your suggestions in the morning

**Comment by jkfurog** [comment]
looks like the `setAndroidNativeModule()` has not been used 
<img width="765" alt="image" src="https://user-images.githubusercontent.com/103121173/181412885-036631a9-4e69-45cc-9a0f-02ea5792ca13.png">

**Comment by jkfurog** [comment]
and also @andresesfm looks like the `selectedOfferIndex` params has not been exposed to `requestSubscription` function in `iap.ts`

<img width="1193" alt="image" src="https://user-images.githubusercontent.com/103121173/181414449-d60082d3-4916-458e-ae39-5d13bdece6fd.png">

**Comment by andresesfm** [comment]
> looks like the `setAndroidNativeModule()` has not been used <img alt="image" width="765" src="https://user-images.githubusercontent.com/103121173/181412885-036631a9-4e69-45cc-9a0f-02ea5792ca13.png">

Good catch, I'm not exporting it

**Comment by andresesfm** [comment]
> and also @andresesfm looks like the `selectedOfferIndex` params has not been exposed to `requestSubscription` function in `iap.ts`
> 
> <img alt="image" width="1260" src="https://user-images.githubusercontent.com/103121173/181414608-ac9499bc-6811-4dae-906b-77324c3a5624.png">

Good catch again, I'm only adding it to the purchase method.

**Comment by SimonDamberg** [comment]
@andresesfm Thanks for your work on this! I am trying out the 9.0.0 beta with our app. What is the expected behaviour? Am I supposed to pass the product-id of the subscription in `getSubscriptions()` to get all the base plans/offers? Do I need to pass the id of the base-plans/offers?

**Comment by andresesfm** [comment]
https://github.com/dooboolab/react-native-iap/pull/1771 will merge shortly to create beta 2

**Comment by andresesfm** [comment]
@SimonDamberg If you use subscription offer then you'd need to pass the offer index when calling `requestSubscription`. If you don't use it, there should be little change. (The subscribe method now takes an object instead of separate parameters but that's it)

**Comment by andresesfm** [comment]
Hello @jkfurog I have published 9.0.0-beta2. However, I can't reproduce the android native error you displayed. I tried enforcing the type but it's marked as unnecessary. Can you please take a look and see if this fixed it for you? If it doesn't, can you please confirm the react-native version you are using? I've tested on 0.66 and .69.1 (same as our CI build)

**Comment by SimonDamberg** [comment]
> @SimonDamberg If you use subscription offer then you'd need to pass the offer index when calling `requestSubscription`. If you don't use it, there should be little change. (The subscribe method now takes an object instead of separate parameters but that's it)

Great! But how do I fetch the different available plans/offers to display in my app? I call `getSubscriptions()` with the product-ids for my two different subscriptions, which both have two different offers (month & year), but only one offer for each is returned (month, which is the offer marked as backwards compatible in Google Play). Are they supposed to show up as different `Subscription` objects? How do I know the offer index?

**Comment by andresesfm** [comment]
@SimonDamberg Yes, use `getSubscriptions`, which returns a List of subscription objects. Each subscription has a list of `subscriptionOfferDetails`. from that list, pick the offer and pass that as `selectedOfferIndex`. I have just updated the types to reflect that list.

Forgive me if I haven't included all the details. I'm updating the doc as we go. I'm trying to do this as interactive as possible.

**Comment by andresesfm** [comment]
published beta3 with fixes to types

**Comment by jkfurog** [comment]
hi @andresesfm I'll check it, thanks you so much !

**Comment by jkfurog** [comment]
hi @andresesfm , I am still getting the Native Android Issues

```
e: /****/node_modules/react-native-iap/android/src/play/java/com/dooboolab/RNIap/RNIapModule.kt: (203, 39): Type mismatch: inferred type is String? but String was expected
e: /****/mobile-frontend/node_modules/react-native-iap/android/src/play/java/com/dooboolab/RNIap/RNIapModuleV4.kt: (199, 39): Type mismatch: inferred type is String? but String was expected
```

My react-native version is `0.63.4`

**Comment by jkfurog** [comment]
and also @andresesfm  if I am not passing any value for `selectedOfferIndex` or I am passing a `null` , I am getting this error
<img width="336" alt="image" src="https://user-images.githubusercontent.com/103121173/181671229-3c087051-6c8b-499d-a394-b57707c7d195.png">

**Comment by andresesfm** [comment]
> hi @andresesfm , I am still getting the Native Android Issues
> 
> ```
> e: /****/node_modules/react-native-iap/android/src/play/java/com/dooboolab/RNIap/RNIapModule.kt: (203, 39): Type mismatch: inferred type is String? but String was expected
> e: /****/mobile-frontend/node_modules/react-native-iap/android/src/play/java/com/dooboolab/RNIap/RNIapModuleV4.kt: (199, 39): Type mismatch: inferred type is String? but String was expected
> ```
> 
> My react-native version is `0.63.4`

Now it makes sense: https://github.com/facebook/react-native/commit/d76556543f96f4d739be3a708b8f6314bb32cc87

**Comment by andresesfm** [comment]
> and also @andresesfm if I am not passing any value for `selectedOfferIndex` or I am passing a `null` , I am getting this error <img alt="image" width="336" src="https://user-images.githubusercontent.com/103121173/181671229-3c087051-6c8b-499d-a394-b57707c7d195.png">

Thank you @jkfurog I have fixed the null issue here: https://github.com/dooboolab/react-native-iap/pull/1776. However, the issue you report when passing empty `selectedOfferIndex` is harder to trace. Are you saying that if you pass a value, things work but if it's null then it fails? also can you get me a stacktrace maybe so I can debug?

**Comment by jkfurog** [comment]
yes @andresesfm if I pass a value aside from null then it works, will try to obtain the logs

**Comment by SimonDamberg** [comment]
@andresesfm Thanks, you are doing amazing work! Unfortunately, the `subscriptionOfferDetails` attribute is undefined for all my returned subscriptions. In Google Play, I have two subscriptions, `*.*.*.nordic` and `*.*.*.usa`, which I am passing to `getSubscriptions()`. Each subscription has two base plans, one monthly and one yearly, both with an offer for a free trial. The monthly base plan for each subscription are marked as backwards-compatible, and are the only ones that show up when calling `getSubscriptions()`.

**Comment by jkfurog** [comment]
hi @SimonDamberg have you implemented this ?

```
RNIap.setAndroidNativeModule(NativeModules.RNIapModule)
RNIap.initConnection()
```

**Comment by SimonDamberg** [comment]
@jkfurog Thank you, I didn't know I had to do that. It works now! :D

**Comment by andresesfm** [comment]
I have fixed the issue when `selectedOfferIndex` is undefined here: https://github.com/dooboolab/react-native-iap/pull/1776 I will create a new beta when that's done

**Comment by andresesfm** [comment]
I have published beta4 with the optional `selectedOfferIdex` fix. It should be truly optional now. Thank you @jkfurog

**Comment by andresesfm** [comment]
@ntcong91 here is where we are tracking those issues

**Comment by jkfurog** [comment]
> I have published beta4 with the optional `selectedOfferIdex` fix. It should be truly optional now. Thank you @jkfurog

thank you @andresesfm I will check it, thanks a lot ! :)

**Comment by andresesfm** [comment]
I just published beta12. It looks pretty stable

**Comment by SimonDamberg** [comment]
@andresesfm Great work! ETA on official release? Do you think there will be any more breaking changes or can I start to migrate our app to it?

**Comment by andresesfm** [comment]
Hello @SimonDamberg, I don't foresee any more breaking changes at this moment. I'm going to focus on any bugs found and promote it to RC if no big issues come along in the next couple of days. Any feedback as far as bug reports are greatly appreciated

**Comment by andresesfm** [comment]
Released 9.0.0-rc.1 to npm after some cleanup and merging the latest fixes from main

**Comment by SimonDamberg** [comment]
@andresesfm Great, I'll migrate our app this week. I can't seem to find 9.0.0-rc.1 on npm, only beta12 is available.

**Comment by SimonDamberg** [comment]
@andresesfm Hmm, I am experiencing the same issue as #1800. Was the fix (#1801) only included in main release and not in the 9.0.0 beta?

**Comment by SimonDamberg** [comment]
Seems like the code is on the next branch but not included in the [9.0.0-beta12](https://github.com/dooboolab/react-native-iap/releases/tag/9.0.0-beta12) release. It is included in [9.0.0-rc.1](https://github.com/dooboolab/react-native-iap/releases/tag/9.0.0-rc.1) so it should be fixed when that is released to npm 😄

**Comment by andresesfm** [comment]
@SimonDamberg , @hyochan took care of the release. I can see it's not available on npm.

**Comment by andresesfm** [comment]
I'm fixing this: https://github.com/dooboolab/react-native-iap/issues/1823 will post updates here

**Comment by jkfurog** [comment]
hi @andresesfm I am still encountering `Parameter specified as non-nll is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter selectedOfferIndices`

when subscribing and not passing `selectedOfferIndices` :
` yield call(IAP.requestSubscription, {sku:product_id});`

<img width="258" alt="image" src="https://user-images.githubusercontent.com/103121173/183552710-6894fd12-9d23-4d75-86fd-f3fc20412267.png">

**Comment by jkfurog** [comment]
and if I pass `[-1]` as `selectedOfferIndices` : 
`yield call(IAP.requestSubscription, {sku:product_id, selectedOfferIndices: [-1]});`

I am getting this error :
<img width="258" alt="image" src="https://user-images.githubusercontent.com/103121173/183556911-ccfd5169-2bf5-4e77-a85b-2db5a3ef9de7.png">

**Comment by SimonDamberg** [comment]
@andresesfm I am getting a hard crash after `requestSubscription()` gets completed. The correct offer shows up and I get the receipt on my order from Google Play, but `currentPurchase` does not update before it crashes. Below is the AndroidRuntimeException when debugging

```
java.lang.RuntimeException: Error receiving broadcast Intent { act=com.android.vending.billing.PURCHASES_UPDATED flg=0x10 pkg=com.qognicafinance.qapsel (has extras) } in com.android.billingclient.api.zzn@fb6d5a1
        at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1689)
        at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7941)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1009)
     Caused by: com.facebook.react.bridge.ObjectAlreadyConsumedException: Map already consumed
        at com.facebook.react.bridge.WritableNativeArray.pushNativeMap(Native Method)
        at com.facebook.react.bridge.WritableNativeArray.pushMap(WritableNativeArray.java:57)
        at com.facebook.react.bridge.Arguments.fromJavaArgs(Arguments.java:183)
        at com.facebook.react.bridge.JavaScriptModuleRegistry$JavaScriptModuleInvocationHandler.invoke(JavaScriptModuleRegistry.java:83)
        at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
        at $Proxy9.emit(Unknown Source)
        at com.dooboolab.RNIap.RNIapModule.sendEvent(RNIapModule.kt:685)
        at com.dooboolab.RNIap.RNIapModule.onPurchasesUpdated(RNIapModule.kt:622)
        at com.android.billingclient.api.zzn.onReceive(com.android.billingclient:billing@@5.0.0:5)
        at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1679)
        at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(Unknown Source:2) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loopOnce(Looper.java:201) 
        at android.os.Looper.loop(Looper.java:288) 
        at android.app.ActivityThread.main(ActivityThread.java:7941) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1009)
```

**Comment by andresesfm** [comment]
Hello everybody, I have released `9.0.0-rc.3` If includes the fix for the reported crash by @SimonDamberg as well as his fix for the type `pricingPhaseList`. 
This RC includes all the refactoring needed to support both one-time purchases as well as subscriptions. The biggest breaking change from rc.1 is that you now need to pass an array of SubscriptionOffer objects instead of an array of selectedOfferTokens. This is because every new subscription sku needs to be paired with an offerToken. Passing the selected Index was cumbersome and more difficult to debug. The one-time purchases now allow for a `skus` array to be passed but it will default to use the single one if provided.

@jkfurog This addresses the issue you reported as well.

Please let me know if any concerns or errors. Sorry it took a few tries but this adds a lot more flexibility for future purchases that allow multiple skus.

**Comment by SimonDamberg** [comment]
@andresesfm Great! I will try the new changes and report if I encounter any issues :)

**Comment by SimonDamberg** [comment]
@andresesfm 9.0.0-rc.3 seems to work great for me! However, I do have one request. Would it be possible to include the offer in the `Purchase` object? As of now, there is no way of knowing what offer the user purchased when processing the purchase, which makes it difficult for me when communicating to our backend.

**Comment by jkfurog** [comment]
hi @andresesfm I am getting this error again after upgrading to `9.0.0-rc.3`

`*/node_modules/react-native-iap/android/src/play/java/com/dooboolab/RNIap/RNIapModule.kt: (442, 81): Type mismatch: inferred type is String? but String was expected`

thanks :)

**Comment by jkfurog** [comment]
hi @andresesfm :) would just like to clarify if this is the intended behavior: for the android we no longer use the `sku` parameter ? and the `subscriptionOffers` param is then required ? just wondering what will be the behavior if that subscription does not have any offer. thank you ! :)

<img width="688" alt="image" src="https://user-images.githubusercontent.com/103121173/183796586-baeb4a7d-6760-4d5e-b9d6-0ba45f4870a2.png">

**Comment by andresesfm** [comment]
> hi @andresesfm I am getting this error again after upgrading to `9.0.0-rc.3`
> 
> `*/node_modules/react-native-iap/android/src/play/java/com/dooboolab/RNIap/RNIapModule.kt: (442, 81): Type mismatch: inferred type is String? but String was expected`
> 
> I am getting it on this part <img alt="image" width="1017" src="https://user-images.githubusercontent.com/103121173/183793170-4c2d9cc7-32c9-4d13-940d-0627d9fba62c.png">
> 
> thanks :)

Thank you, I will fix it for older versions of RN

**Comment by andresesfm** [comment]
> hi @andresesfm :) would just like to clarify if this is the intended behavior: for the android we no longer use the `sku` parameter ? and the `subscriptionOffers` param is then required ? just wondering what will be the behavior if that subscription does not have any offer. thank you ! :)
> 
> <img alt="image" width="688" src="https://user-images.githubusercontent.com/103121173/183796586-baeb4a7d-6760-4d5e-b9d6-0ba45f4870a2.png">

Hello @jkfurog. That is correct, we no longer use sku for Android. Now subscriptionOffers is required. My understanding is that every subscription you query by calling `getSubscriptions()` will contain at least one `subscriptionOfferDetails` and that will always have an `offerToken`

**Comment by jkfurog** [comment]
noted @andresesfm thank you so much ! :) aside from the `inferred type is String? but String was expected` everything seems working on my end

**Comment by andresesfm** [comment]
`9.0.0-rc.4` fixes the null check. It also adds some documentation to the process and it fixes the common type.

**Comment by andresesfm** [comment]
I have created the following discussion: https://github.com/dooboolab/react-native-iap/discussions/1852 for the release of 9.0.0 with Google Billing Library v5. Please use this chance to report any final issues

**Comment by andresesfm** [comment]
9.0.0 has been released

**Comment by roots-ai** [comment]
There are no subscriptionOffers and therefore I am sending an empty array instead
 `await RNIap.requestSubscription({sku: sku, subscriptionOffers: []});` 

But I am still getting the following error "subscriptionOffers are required for Google Play Subscriptions. @andresesfm

**Comment by andresesfm** [comment]
You get them from `getSubscriptions()` @roots-ai

**Comment by omidbarcelona** [comment]
> There are no subscriptionOffers and therefore I am sending an empty array instead `await RNIap.requestSubscription({sku: sku, subscriptionOffers: []});`
> 
> But I am still getting the following error "subscriptionOffers are required for Google Play Subscriptions. @andresesfm

After using `RNIap.getSubscriptions()` and getting the `subscriptionOfferDetails`, how should I give inputs to `RNIap.requestSubscription()`?  I ask this question because I am also getting this error "subscriptionOffers are required for Google Play Subscriptions". 
option 1) 
`const subscriptionOffers = [{
      sku: sku,
      offerToken
    }]
const result = RNIap.subscriptionOffers(subscriptionOffers)
`
option 2)
`const subscriptionOffers = [{
      sku: sku,
      offerToken: offerToken
    }]
const result = RNIap.subscriptionOffers(subscriptionOffers)
`
option 3) 
`...`

**Comment by omidbarcelona** [comment]
> > There are no subscriptionOffers and therefore I am sending an empty array instead `await RNIap.requestSubscription({sku: sku, subscriptionOffers: []});`
> > But I am still getting the following error "subscriptionOffers are required for Google Play Subscriptions. @andresesfm
> 
> After using `RNIap.getSubscriptions()` and getting the `subscriptionOfferDetails`, how should I give inputs to `RNIap.requestSubscription()`? I ask this question because I am also getting this error "subscriptionOffers are required for Google Play Subscriptions". option 1) `const subscriptionOffers = [{ sku: sku, offerToken }] const result = RNIap.subscriptionOffers(subscriptionOffers) ` option 2) `const subscriptionOffers = [{ sku: sku, offerToken: offerToken }] const result = RNIap.subscriptionOffers(subscriptionOffers) ` option 3) `...`

An example of getting  requestSubscription

> There are no subscriptionOffers and therefore I am sending an empty array instead `await RNIap.requestSubscription({sku: sku, subscriptionOffers: []});`
> 
> But I am still getting the following error "subscriptionOffers are required for Google Play Subscriptions. @andresesfm



> There are no subscriptionOffers and therefore I am sending an empty array instead `await RNIap.requestSubscription({sku: sku, subscriptionOffers: []});`
> 
> But I am still getting the following error "subscriptionOffers are required for Google Play Subscriptions. @andresesfm

@roots-ai & @andresesfm 
An issue for the error of "subscriptionOffers are required for Google Play Subscriptions." can be sending the subscriptionOffers to requestSubscription as "RNIap.requestSubscription(subscriptionOffers)" instead of "RNIap.requestSubscription(**{**subscriptionOffers**}**)", see **{ }** around subscriptionOffers.
See below an example that worked for me.
```
 const subscriptionOffers = [{
            sku,
            offerToken,
        }]
        RNIap.requestSubscription({ subscriptionOffers }).then((result) => {
            console.log("result: " + JSON.stringify(result))
        }).catch(e => console.log('requestSubscription error: ', e))
```

**Comment by shivanitp** [comment]
> > > There are no subscriptionOffers and therefore I am sending an empty array instead `await RNIap.requestSubscription({sku: sku, subscriptionOffers: []});`
> > > But I am still getting the following error "subscriptionOffers are required for Google Play Subscriptions. @andresesfm
> > 
> > 
> > After using `RNIap.getSubscriptions()` and getting the `subscriptionOfferDetails`, how should I give inputs to `RNIap.requestSubscription()`? I ask this question because I am also getting this error "subscriptionOffers are required for Google Play Subscriptions". option 1) `const subscriptionOffers = [{ sku: sku, offerToken }] const result = RNIap.subscriptionOffers(subscriptionOffers) ` option 2) `const subscriptionOffers = [{ sku: sku, offerToken: offerToken }] const result = RNIap.subscriptionOffers(subscriptionOffers) ` option 3) `...`
> 
> An example of getting requestSubscription
> 
> > There are no subscriptionOffers and therefore I am sending an empty array instead `await RNIap.requestSubscription({sku: sku, subscriptionOffers: []});`
> > But I am still getting the following error "subscriptionOffers are required for Google Play Subscriptions. @andresesfm
> 
> > There are no subscriptionOffers and therefore I am sending an empty array instead `await RNIap.requestSubscription({sku: sku, subscriptionOffers: []});`
> > But I am still getting the following error "subscriptionOffers are required for Google Play Subscriptions. @andresesfm
> 
> @roots-ai & @andresesfm An issue for the error of "subscriptionOffers are required for Google Play Subscriptions." can be sending the subscriptionOffers to requestSubscription as "RNIap.requestSubscription(subscriptionOffers)" instead of "RNIap.requestSubscription(**{**subscriptionOffers**}**)", see **{ }** around subscriptionOffers. See below an example that worked for me.
> 
> ```
>  const subscriptionOffers = [{
>             sku,
>             offerToken,
>         }]
>         RNIap.requestSubscription({ subscriptionOffers }).then((result) => {
>             console.log("result: " + JSON.stringify(result))
>         }).catch(e => console.log('requestSubscription error: ', e))
> ```

can you explain how to upgrade or downgrade the subscription with this 
how to pass old sku or purchase token in this subscriptionOffers variable

**Comment by andresesfm** [comment]
You are not supposed to pass the previous SKU but the old purchase token

**Comment by nl-danish** [comment]
Hello everyone,

Is there a documentation for migrating to 9.0.0? I'm currently on a really old version, which is 7.5.1.
Please, let me know. Thanks.
